<a href="https://colab.research.google.com/github/Jeevesh8/PyTorch-Learning-NBs/blob/master/indexing_using__gather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
x = torch.tensor([[2.,3.,4], [4,5,7.8]])

In [0]:
#doesn't work
#y = torch.tensor([1,2]) does not work      #Same number of dimensions as x must be there
#y = torch.tensor([1.,2]) does not work     #y Must be int/long

In [2]:
y = torch.tensor([[1],[2]])
print(x.gather(1, y))                       #Will select elements along 1th dimension

tensor([[3.0000],
        [7.8000]])


In [3]:
y = torch.tensor([[1,2],[0,0]]) 
print(x.gather(1,y))                        #Can select any number of elements along 1th dimension

tensor([[3., 4.],
        [4., 4.]])


In [0]:
#doesn't work:- Trying to pick 0th and 1th tensor along the 0th dimension 
#y = torch.tensor([[0],[1]])<---|-------|                   |
#print(x.gather(0,y))<---------------------------------------

In [0]:
#doesn't work 
#y = torch.tensor([[0],[1],[0]])            #To gather from 0th dimension of tensor of size n1Xn2 use  matrix of size 1Xn2 and
#print(x.gather(0,y))                       #To gather from 1th use tensor of size n1X1

In [4]:
y = torch.tensor([[0,1,0]])                 #You have to specify an element to select from each column of the 2X3 matrix,
print(x.gather(0,y))                        #When you are selecting along dimension corresponding to rows

tensor([[2., 5., 4.]])
